
name: a2
on:
  workflow_dispatch:
jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: curl https://api.github.com/repos/${{ github.repository }}/releases/latest

