
name: a2
on:
  workflow_dispatch:
jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run:  echo $(curl https://api.github.com/users/$(echo ${{ github.repository }} | sed "s/\/.*//g") 2>/dev/null  |grep '"name": "'|sed 's/  "name": "//'|sed 's/",//' 2>/dev/null)

