name: '测试'
description: '测试'
runs: 
  using: "composite"
  steps:
        - run: |
            echo ${{ github.workspace }}
            echo "11" >> 00
            echo "22" >> 00
            echo "33" >> 00
            echo -e "::error ::检查到软件包依赖问题：\n$(cat 00)"
            echo "::notice ::你编译的架构为，子架构为"
            env
          shell: bash

