name: 'Hello World'
description: 'test'
runs: 
  using: "composite"
  steps:
        - run: echo ${{ github.workspace }}
          shell: bash
        - run: echo "11" >> 00
          shell: bash
        - run: echo "22" >> 00
          shell: bash
        - run: echo "33" >> 00
          shell: bash
        - run: echo -e "::error ::检查到软件包依赖问题：\n$(cat 00)"
          shell: bash
        - run: echo "::notice ::你编译的架构为，子架构为"
          shell: bash
