
name: a2
on:
  workflow_call:
  workflow_dispatch:
jobs:

  job1:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: 记录开始时间
        id: time
        run: |
          sudo timedatectl set-timezone "Asia/Shanghai"
          starttime=$(date +"%y.%m.%d-%H")
          echo starttime=$starttime >> "$GITHUB_OUTPUT"
          echo starttime=$starttime >> "$GITHUB_ENV"
          echo "::notice ::编译开始时间为：$starttime"
          
      - name: 将存储库签出到运行器
        uses: actions/checkout@v3

      - name: aa
        uses: ./.github/workflows
        
      - name: 建立工作文件夹
        run: |
          export CMZJ_PACKAGE_ROOT_PATH="$WORKSPACE_ROOT_PATH/cmzj_package"
          export CMZJ_PATCH_ROOT_PATH="$WORKSPACE_ROOT_PATH/cmzj_patch"
          export LOG_PATH="$WORKSPACE_ROOT_PATH/log"
          echo "CMZJ_PACKAGE_ROOT_PATH=$CMZJ_PACKAGE_ROOT_PATH" >> $GITHUB_ENV
          echo "CMZJ_PATCH_ROOT_PATH=$CMZJ_PATCH_ROOT_PATH" >> $GITHUB_ENV
          echo "LOG_PATH=$LOG_PATH" >> $GITHUB_ENV
        

      - name: 建立工作文件夹
        run: ls -la $(find . -type d)

      - name: 建立工作文件夹
        id: set-matrix
        run: echo "matrix={'include':[{'project':'foo','config':'Debug'},{'project':'bar','config':'Release'}]}" >> $GITHUB_OUTPUT

  example_matrix:
    runs-on: ubuntu-latest
    needs: job1
    strategy:
        matrix: ${{ fromJSON(needs.job1.outputs.matrix) }}
    steps:
     - name: 建立工作文件夹
       run: |
          echo "${{ matrix.project }}"
          echo "${{ matrix.config }}"
