
name: a2
on:
  workflow_call:
  workflow_dispatch:
jobs:

  build:
    runs-on: ubuntu-latest
    outputs:
      aaa: ${{ steps.a.outputs.aaa }}
    steps:
      - name: 将存储库签出到运行器
        uses: actions/checkout@v3
        
      - name: 建立工作文件夹
        run: |
          export CMZJ_PACKAGE_ROOT_PATH="$WORKSPACE_ROOT_PATH/cmzj_package"
          export CMZJ_PATCH_ROOT_PATH="$WORKSPACE_ROOT_PATH/cmzj_patch"
          export LOG_PATH="$WORKSPACE_ROOT_PATH/log"
          echo "CMZJ_PACKAGE_ROOT_PATH=$CMZJ_PACKAGE_ROOT_PATH" >> $GITHUB_ENV
          echo "CMZJ_PATCH_ROOT_PATH=$CMZJ_PATCH_ROOT_PATH" >> $GITHUB_ENV
          echo "LOG_PATH=$LOG_PATH" >> $GITHUB_ENV
        
      - name: 建立工作文件夹
        uses: ./.github/workflows/

      - name: 建立工作文件夹
        run: ls -la $(find . -type d)

      - name: 建立工作文件夹
        id: a
        run: echo "aaa=['a','b','c']" >> $GITHUB_OUTPUT

  example_matrix:
    runs-on: ubuntu-latest
    needs: build
    strategy:
      matrix:
        aa: ${{ fromJSON(needs.build.outputs.aaa) }}
    steps:
     - name: 建立工作文件夹
       run: |
          echo "${{ matrix.aa }}"
