# This is a basic workflow to help you get started with Actions

name: q1
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: 建立工作文件夹
        run:  |
          echo ${{ github.workspace }}
          echo "::error ::OpenWrt-K不支持为5.10以下内核打补丁，如需编译请删除此步骤与turboacc的相关的步骤"
          echo "::notice ::你编译的架构为，子架构为"
          
          
